# Exploratory Data Anaysis
## Load Dependencies

In [1]:
import csv
import pandas as pd
import numpy as np
from functools import reduce
import requests
import time
from datetime import datetime
import requests.exceptions
import os
import json
import random
import re
from collections import defaultdict

## Load Dataframes

In [6]:
wine_scores = pd.read_csv('data\clean\cleaned_combined_wine_data.csv')
weather_data = pd.read_csv('data\clean\combined_weather_data_clean.csv')

In [7]:
# Sanity Check
wine_scores.head()

Wine Name Region 1 Region 2 Region 3  \
0    Calem 1961 Colheita Tawny Port (Port)      NaN     Port      NaN   
1        Calem 1961 Colheita Tawny  (Port)      NaN     Port      NaN   
2   Warre's 1961 Reserve Tawny Port (Port)      NaN     Port      NaN   
3  Wiese & Krohn 1961 Colheita Port (Port)      NaN     Port      NaN   
4       Cossart Gordon 1962 Bual (Madeira)      NaN  Madeira      NaN   

    Country  Score  Price          Winery     Variety  Vintage  
0  Portugal     95  320.0           Calem  Port Blend     1961  
1  Portugal     95  320.0           Calem        Port     1961  
2  Portugal     89  111.0         Warre's  Port Blend     1961  
3  Portugal     92  200.0   Wiese & Krohn  Port Blend     1961  
4  Portugal     96  355.0  Cossart Gordon     Madeira     1962

In [5]:
weather_data.head()

Station ID    Country                   City  Data Type  Year    Jan  \
0        5046  INDONESIA  KIJANG TANJUNG PINANG          4  1993   25.6   
1        5046  INDONESIA  KIJANG TANJUNG PINANG          4  1995   26.0   
2        5046  INDONESIA  KIJANG TANJUNG PINANG          5  1993  246.6   
3        5046  INDONESIA  KIJANG TANJUNG PINANG          5  1995  388.0   
4        5046  INDONESIA  KIJANG TANJUNG PINANG          6  1993   29.6   

     Feb    Mar    Apr    May    Jun    Jul    Aug    Sep    Oct    Nov    Dec  
0   25.6   25.7   26.0   25.9   26.8   25.8   26.3   25.8   25.4   25.4   25.9  
1   25.6   25.9   26.0   26.6   26.6   26.3   26.2   26.7   26.1   25.9   25.6  
2   61.9  285.8  324.2  424.1  169.6  261.7  157.9  240.3  398.5  473.6  683.9  
3  325.1  190.7  357.9  299.5  334.3  250.9  213.4  265.6  496.3  630.8  277.1  
4   30.7   30.6   31.3   29.8   31.2   30.7   31.3   30.7   30.3   29.9   29.9

## Working Dataframes
We need to create some temporary working dataframes for us to do preliminary data exploration. First lets reduce the amount of weather data we have by just grabbing the data from countries and years that we have wines for.

In [10]:
wine_data_df = pd.read_csv('data\clean\cleaned_combined_wine_data.csv')
weather_data_df = pd.read_csv('data\clean\combined_weather_data_clean.csv')

# Rename the 'Vintage' column in wine_data_df to 'Year' for consistency
wine_data_df.rename(columns={'Vintage': 'Year'}, inplace=True)

# Standardize country names in wine data to uppercase for matching
wine_data_df['Country'] = wine_data_df['Country'].str.upper()

# Filter the weather data to only include rows that match the Country and Year in the wine data
matched_weather_data = weather_data_df[weather_data_df[['Country', 'Year']].apply(tuple, 1).isin(wine_data_df[['Country', 'Year']].apply(tuple, 1))]

# Reset the index of the DataFrame
matched_weather_data.reset_index(drop=True, inplace=True)

# Display the first few rows of the filtered weather data
matched_weather_data.head()

Station ID      Country                        City  Data Type  Year   Jan  \
0           0    AUSTRALIA  SCONE SOIL CONS          0          4  1985  24.6   
1           0    AUSTRALIA  SCONE SOIL CONS          0          4  1987  25.7   
2           0    AUSTRALIA  SCONE SOIL CONS          0          5  1985   4.6   
3           0    AUSTRALIA  SCONE SOIL CONS          0          5  1987  90.6   
4        6600  SWITZERLAND              ST. CHRISCHONA          4  2004   0.9   

    Feb   Mar   Apr   May   Jun   Jul    Aug   Sep    Oct   Nov    Dec  
0  22.4  21.5  17.7  14.2  10.2  10.6   11.3  13.2   17.2  19.1   22.8  
1  24.7  19.6  17.9  14.2  12.0  10.1   13.1  14.8   17.1  20.0   22.6  
2  88.8  48.6  53.8  36.2  55.2  17.0   45.2  76.4  143.2  33.4  121.6  
3   4.8  82.8   5.0  73.4  20.8   9.8  110.2  19.2   42.6  41.0  113.8  
4   2.3   4.8   9.5  11.7  15.7  17.2   17.7  14.4   10.7   4.0    0.2

Now we want to get rid of the Data Type column, so its easier for someone to read all relevant weather data in one dataframe. Atomosphereric pressure isn't relevant for what we are trying to calculate, and not to mention not all locations measure atomosphereric pressure, so we will be getting ride of data type 2 and 3 if it ever pops up.

In [16]:
# Function to rename columns based on the data type
def rename_columns(df, data_type):
    prefix = {
        4: 'daily_temp',
        5: 'precipitation',
        6: 'daily_temp_MAX',
        7: 'daily_temp_MIN',
        8: 'humidity'
    }.get(data_type, 'unknown')

    month_cols = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    new_month_cols = [f'{prefix}_{month}' for month in month_cols]
    rename_dict = dict(zip(month_cols, new_month_cols))
    df.rename(columns=rename_dict, inplace=True)
    return df

# Splitting the DataFrame into separate DataFrames based on Data Type
dfs = {}
for dtype in [4, 5, 6, 7, 8]:
    df = matched_weather_data[matched_weather_data['Data Type'] == dtype].copy()
    df = rename_columns(df, dtype)
    dfs[dtype] = df

# Drop the 'Data Type' column from each DataFrame and rename the month columns
for dtype, df in dfs.items():
    df = df.drop(columns=['Data Type'])
    df = rename_columns(df, dtype)
    dfs[dtype] = df
    
# Merge the DataFrames back together with explicit suffixes for overlapping columns
merged_weather_df = reduce(lambda left, right: pd.merge(left, right, on=['Station ID', 'Country', 'City', 'Year'], how='outer', suffixes=('', '_duplicate')), dfs.values())

# Remove any columns that were duplicated during the merge
merged_weather_df = merged_weather_df[[col for col in merged_weather_df.columns if not col.endswith('_duplicate')]]

# Reset the index of the DataFrame
merged_weather_df.reset_index(drop=True, inplace=True)

# Check results
merged_weather_df.head()

Station ID      Country                        City  Year  daily_temp_Jan  \
0           0    AUSTRALIA  SCONE SOIL CONS          0  1985            24.6   
1           0    AUSTRALIA  SCONE SOIL CONS          0  1987            25.7   
2        6600  SWITZERLAND              ST. CHRISCHONA  2004             0.9   
3        6601  SWITZERLAND           BASEL / BINNINGEN  2004             2.3   
4        6601  SWITZERLAND           BASEL / BINNINGEN  2011             2.4   

   daily_temp_Feb  daily_temp_Mar  daily_temp_Apr  daily_temp_May  \
0            22.4            21.5            17.7            14.2   
1            24.7            19.6            17.9            14.2   
2             2.3             4.8             9.5            11.7   
3             3.0             5.7            10.6            13.2   
4             3.9             7.5            13.4            16.6   

   daily_temp_Jun  ...  humidity_Mar  humidity_Apr  humidity_May  \
0            10.2  ...           NaN           NaN           NaN   
1            12.0  ...           NaN           NaN           NaN   
2            15.7  ...           NaN           NaN           NaN   
3            17.7  ...           NaN           NaN           NaN   
4            18.1  ...           NaN           NaN           NaN   

   humidity_Jun  humidity_Jul  humidity_Aug  humidity_Sep  humidity_Oct  \
0           NaN           NaN           NaN           NaN           NaN   
1           NaN           NaN           NaN           NaN           NaN   
2           NaN           NaN           NaN           NaN           NaN   
3           NaN           NaN           NaN           NaN           NaN   
4           NaN           NaN           NaN           NaN           NaN   

   humidity_Nov  humidity_Dec  
0           NaN           NaN  
1           NaN           NaN  
2           NaN           NaN  
3           NaN           NaN  
4           NaN           NaN  

[5 rows x 64 columns]

In [17]:
merged_weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40321 entries, 0 to 40320
Data columns (total 64 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Station ID          40321 non-null  int64  
 1   Country             40321 non-null  object 
 2   City                40321 non-null  object 
 3   Year                40321 non-null  int64  
 4   daily_temp_Jan      39238 non-null  float64
 5   daily_temp_Feb      39238 non-null  float64
 6   daily_temp_Mar      39238 non-null  float64
 7   daily_temp_Apr      39238 non-null  float64
 8   daily_temp_May      39238 non-null  float64
 9   daily_temp_Jun      39238 non-null  float64
 10  daily_temp_Jul      39238 non-null  float64
 11  daily_temp_Aug      39238 non-null  float64
 12  daily_temp_Sep      39238 non-null  float64
 13  daily_temp_Oct      39238 non-null  float64
 14  daily_temp_Nov      39238 non-null  float64
 15  daily_temp_Dec      39238 non-null  float64
 16  prec

In [18]:
# Save dataframe to CSV
merged_weather_df.to_csv('data\clean\merged_weather.csv', index=False)

Next we will filter out wine data that have matching location and vintages.

In [21]:
# Load Dataframes
wine_data = pd.read_csv('data/clean/cleaned_combined_wine_data.csv')
merged_weather_df = pd.read_csv('data\clean\merged_weather.csv')

# Create a temporary DataFrame with unique city-country pairs
unique_city_country = merged_weather_df[['City', 'Country']].drop_duplicates()
unique_city_country['City'] = unique_city_country['City'].str.upper()
unique_city_country['City Words'] = unique_city_country['City'].apply(lambda x: x.split())

# Function to check for any matching word and country match
def any_matching_word_and_country(row, city_country_df):
    for region_key in ['Region 1', 'Region 2', 'Region 3']:
        region = row[region_key]
        if pd.notna(region):
            region_words = set(region.upper().split())
            for _, city_country_row in city_country_df.iterrows():
                if any(word in region_words for word in city_country_row['City Words']) and row['Country'].upper() == city_country_row['Country'].upper():
                    return True
    return False

# Ensure all relevant columns are strings and handle NaNs
wine_data[['Region 1', 'Region 2', 'Region 3']] = wine_data[['Region 1', 'Region 2', 'Region 3']].fillna('').astype(str)
wine_data['Country'] = wine_data['Country'].fillna('').astype(str)

# Filter wine_data
filtered_wine_data = wine_data[wine_data.apply(lambda row: any_matching_word_and_country(row, unique_city_country), axis=1)]

# Check result
filtered_wine_data.head()

Wine Name      Region 1  \
43  Bodegas Dios Baco S.L. NV 1970 Oxford Pedro Xi...     Andalucia   
75           Adega de Favaios 1980  Moscatel do Douro                 
77  Adega de Favaios 1980 Moscatel (Moscatel do Do...                 
79          Cuva Vella 1980 Vintage Muscat (Valencia)       Levante   
87  Moulin Touchais 1982 Chenin Blanc (Coteaux du ...  Loire Valley   

             Region 2          Region 3   Country  Score  Price  \
43                                Jerez     Spain     85   40.0   
75  Moscatel do Douro                    Portugal     93  137.0   
77  Moscatel do Douro                    Portugal     93  137.0   
79                             Valencia     Spain     90   65.0   
87                     Coteaux du Layon    France     95   64.0   

                    Winery       Variety  Vintage  
43  Bodegas Dios Baco S.L.        Sherry     1970  
75        Adega de Favaios      Moscatel     1980  
77        Adega de Favaios        Muscat     1980  
79              Cuva Vella        Muscat     1980  
87         Moulin Touchais  Chenin Blanc     1982

In [22]:
# Reset the index of the DataFrame
filtered_wine_data.reset_index(drop=True, inplace=True)

# Check result
filtered_wine_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16760 entries, 0 to 16759
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Wine Name  16760 non-null  object 
 1   Region 1   16760 non-null  object 
 2   Region 2   16760 non-null  object 
 3   Region 3   16760 non-null  object 
 4   Country    16760 non-null  object 
 5   Score      16760 non-null  int64  
 6   Price      15406 non-null  float64
 7   Winery     16760 non-null  object 
 8   Variety    16705 non-null  object 
 9   Vintage    16760 non-null  int64  
dtypes: float64(1), int64(2), object(7)
memory usage: 1.3+ MB


In [24]:
# Save dataframe to CSV
filtered_wine_data.to_csv(r'data\clean\filtered_wine_data.csv', index=False)

With the low amount of match rate, we would need to approach this differently. We would need to use a weather API to obtain the weather information for wines that are missing related weather data. Keep in mind, some wines don't have an associated specific city and some wines just have a wine region. So what would make more sense is to have an api look up the geocoordinates of the wine region and then plug it into a weather API to get the necessary information.

## Implementing an API Solution

The following script uses Bing API to grab geocoordinates of regions mentioned in our list of wines, then uses the geocoordinates to grab climate data from NOAA api. Since we are using free service level of these APIs we need the script to stop when we hit the daily request limit. 

To start off let's create a proof of concept test script that tests out all the logic we need for our full script. The following script samples a random row from our clean wine csv file and try to return weather databased on it.

In [145]:
# Constants for rate limiting
NOAA_RATE_LIMIT = 0.2  # seconds between requests
NOAA_DAILY_LIMIT = 10000
noaa_request_count = 0  # Initialize request count

# Function to clean and prepare keywords
def clean_keywords(text):
    if pd.isna(text):
        return ""
    # Remove text within parentheses
    text = re.sub(r'\(.*?\)', '', text).strip()
    return text

# Function to create variations of the winery name
def create_winery_variations(winery):
    variations = ["Wines", "Wine", "Vineyard", "Estate", "Winery", "Vineyards"]
    return [f"{winery} {variation}" for variation in variations] + [winery]

# Function to construct search query
def construct_query(row, winery_variations):
    regions = [clean_keywords(row['Region 1']), clean_keywords(row['Region 2']), clean_keywords(row['Region 3'])]
    country = clean_keywords(row['Country'])

    # Construct different combinations
    combinations = []
    for winery_variation in winery_variations:
        for i in range(len(regions)):
            for j in range(i, len(regions)):
                query_parts = [winery_variation] + regions[i:j+1] + [country]
                combinations.append(' '.join(filter(None, query_parts)))

    return combinations, regions, country

# Function to calculate the bounding box
def get_gps_bounding_box(latitude, longitude, deg_lat=1.0, deg_lon=1.0):
    n = min(90, latitude + deg_lat)
    s = max(-90, latitude - deg_lat)
    e = min(180, longitude + deg_lon)
    w = max(-180, longitude - deg_lon)
    return n, w, s, e

# Function to find weather stations by bounding box with rate limiting
def get_stations_by_bounding_box(lat, lon, api_token):
    global noaa_request_count
    if noaa_request_count >= NOAA_DAILY_LIMIT:
        print("NOAA daily request limit reached.")
        return []

    time.sleep(NOAA_RATE_LIMIT)
    n, w, s, e = get_gps_bounding_box(lat, lon)
    url = f"https://www.ncei.noaa.gov/access/services/search/v1/data?dataset=global-summary-of-the-month&boundingBox={n},{w},{s},{e}&dataTypes=TMIN,TMAX,PRCP,TAVG&limit=10&offset=0"
    headers = {'token': api_token}
    try:
        response = requests.get(url, headers=headers, timeout=10)  # 10 seconds timeout
        noaa_request_count += 1
        if response.status_code == 200:
            stations_data = response.json().get('results', [])
            valid_stations = []
            for station in stations_data:
                station_id = station['id']
                # Extract the valid part of the station ID
                valid_station_id = station_id.split(':')[1].split('.')[0]
                valid_stations.append(valid_station_id)
            return valid_stations
    except requests.exceptions.Timeout:
        print("NOAA request timed out.")
    except Exception as e:
        print(f"Error in NOAA request: {e}")
    return []

# Function to get monthly climate data for a station with rate limiting
def get_mly_climate_data_for_station(station_id, vintage_year, api_token):
    global noaa_request_count
    if noaa_request_count >= NOAA_DAILY_LIMIT:
        print("NOAA daily request limit reached.")
        return {}

    start_date = f"{vintage_year}-01-01"
    end_date = f"{vintage_year}-12-31"
    time.sleep(NOAA_RATE_LIMIT)
    url = f"https://www.ncei.noaa.gov/access/services/data/v1?dataset=global-summary-of-the-month&dataTypes=TMIN,TMAX,PRCP,TAVG&stations={station_id}&startDate={start_date}&endDate={end_date}&format=json&units=standard&includeAttributes=false"
    headers = {'token': api_token}

    try:
        response = requests.get(url, headers=headers, timeout=10)
        noaa_request_count += 1

        if response.status_code == 200:
            monthly_data_raw = response.json()
            monthly_data = {f"{data_type}_{month}": [] for data_type in ['TMIN', 'TMAX', 'PRCP', 'TAVG'] for month in range(1, 13)}

            for record in monthly_data_raw:
                month = int(record['DATE'].split('-')[1])
                for data_type in ['TMIN', 'TMAX', 'PRCP', 'TAVG']:
                    if record.get(data_type) is not None:
                        monthly_data[f"{data_type}_{month}"].append(float(record[data_type]))

            # Averaging the data
            averaged_data = {key: sum(values) / len(values) if values else None for key, values in monthly_data.items()}
            return averaged_data

    except requests.exceptions.Timeout:
        print("NOAA request timed out.")
    except Exception as e:
        print(f"Error in NOAA request: {e}")
    return {}

# Function to check if address matches the country
def is_country_match(country, address):
    return country.lower() in address.lower()

# Function to check if address matches any of the regions and country
def is_region_country_match(regions, country, address):
    region_country_text = " ".join([r for r in regions if r] + [country]).lower()
    return any(region.lower() in address.lower() for region in region_country_text.split()) and country.lower() in address.lower()

# Read CSV file
df = pd.read_csv('data/clean/cleaned_combined_wine_data.csv')

# Select a random row
random_row = df.sample().iloc[0]

# Get winery name and create variations
winery = clean_keywords(random_row['Winery'])
winery_variations = create_winery_variations(winery)

# Construct queries
queries, regions, country = construct_query(random_row, winery_variations)

# Bing Maps API Key
bing_maps_key = 'Insert Key'

# NOAA API token
noaa_api_token = "Insert Key"

# Function to search using Bing Maps API
def search_address(query):
    url = f"http://dev.virtualearth.net/REST/v1/Locations?query={query}&key={bing_maps_key}"
    response = requests.get(url)
    if response.status_code == 200:
        return response.json()
    return None

# Function to extract address, location name, and geocoordinates from the result
def extract_address_info(result):
    if result and 'resourceSets' in result:
        resources = result['resourceSets'][0]['resources']
        if resources:
            location_name = resources[0]['name']
            address = resources[0]['address']['formattedAddress']
            coordinates = resources[0]['point']['coordinates'] if 'point' in resources[0] else None
            return location_name, address, coordinates
    return None, None, None

# Function to check if the winery name is part of the business name in the location
def is_correct_business_match(winery_variations, location_name, address, country):
    return any(winery_variation.lower() in location_name.lower() for winery_variation in winery_variations) and is_country_match(country, address)

# Function to find the best match for the winery
def find_best_match(queries, winery_variations, regions, country):
    best_match = None
    for query in queries:
        result = search_address(query)
        location_name, address, coordinates = extract_address_info(result)
        if location_name and address and coordinates:
            if is_correct_business_match(winery_variations, location_name, address, country):
                return (query, location_name, address, coordinates)
            elif is_region_country_match(regions, country, address) and not best_match:
                best_match = (query, location_name, address, coordinates)

    return best_match

# Find the best match
best_match = find_best_match(queries, winery_variations, regions, country)
if best_match:
    query, location_name, address, coordinates = best_match
    print(f"Address Found: {query}, {location_name}, {address}, {coordinates}")
    lat, lon = coordinates
    station_results = get_stations_by_bounding_box(lat, lon, noaa_api_token)

    aggregated_weather_data = {
        "TMAX": defaultdict(list),
        "TMIN": defaultdict(list),
        "PRCP": defaultdict(list),
        "TAVG": defaultdict(list)
    }

    # Collecting data from each station
    for station_id in station_results:
        station_weather_data = get_mly_climate_data_for_station(station_id, vintage_year, noaa_api_token)
        if station_weather_data:
            for key, value in station_weather_data.items():
                if value is not None:
                    metric, month = key.split('_')
                    aggregated_weather_data[metric][int(month)].append(value)

    # Averaging the data across all stations
    averaged_weather_data = {}
    for metric, monthly_values in aggregated_weather_data.items():
        for month in range(1, 13):
            if monthly_values[month]:
                avg_value = sum(monthly_values[month]) / len(monthly_values[month])
                averaged_weather_data[f"{metric}_{month}"] = avg_value
            else:
                averaged_weather_data[f"{metric}_{month}"] = None

    print("Averaged Weather Data:", averaged_weather_data)
else:
    print("No valid address found.")

Address Found: Gadais Pere et Fils Wines Loire Valley France, Loire Valley, Indre-et-Loire, France, Loire Valley, Indre-et-Loire, France, [47.39888763, 0.7027778]
Averaged Weather Data: {'TMAX_1': 30.84444444444444, 'TMAX_2': 37.166666666666664, 'TMAX_3': 46.288888888888884, 'TMAX_4': 59.333333333333336, 'TMAX_5': 68.56, 'TMAX_6': 79.12, 'TMAX_7': 87.59, 'TMAX_8': 83.44, 'TMAX_9': 75.41, 'TMAX_10': 64.24444444444445, 'TMAX_11': 52.57777777777778, 'TMAX_12': 42.1, 'TMIN_1': 13.211111111111114, 'TMIN_2': 16.266666666666666, 'TMIN_3': 26.54444444444444, 'TMIN_4': 37.5875, 'TMIN_5': 48.279999999999994, 'TMIN_6': 57.160000000000004, 'TMIN_7': 63.89, 'TMIN_8': 60.03000000000001, 'TMIN_9': 51.85000000000001, 'TMIN_10': 41.22222222222222, 'TMIN_11': 30.299999999999997, 'TMIN_12': 22.766666666666666, 'PRCP_1': 1.59, 'PRCP_2': 1.9749999999999999, 'PRCP_3': 2.6, 'PRCP_4': 4.241428571428572, 'PRCP_5': 4.363333333333333, 'PRCP_6': 3.397777777777778, 'PRCP_7': 3.9377777777777783, 'PRCP_8': 6.4455555

After running the script a few times, it is obvious it is not perfect. Not all locations can be pinpointed to the exact city or village that each wine is produced. This is mostly the fault of the wine data we have, since not all data have detailed wine location information. This could skew our data to higher class wines where more detailed location information is provided. However the good news is that there are low class wines from smaller countries where even if there isn't perfect location data, the difference in weather data is within a margin of error (unless there are some geographic feature that makes certain areas to have different weather pattern). Also there are wines where only the province or state is listed, so using the averaged weather data in the area would give a good indication, since these wines are meant to represent that they are made with grapes all across the state, county, or province.

Next we can write a full script that iterate through a CSV. Here to make sure we can get a result to make sure the script works, I've created a CSV file that contains a small sample of wines for the script to be tested on.

In [146]:
# Constants for rate limiting
NOAA_RATE_LIMIT = 0.2  # seconds between requests
NOAA_DAILY_LIMIT = 10000
noaa_request_count = 0  # Initialize request count

# Bing Maps API Key (replace with your key)
bing_maps_key = 'Insert Key'

# NOAA API token (replace with your token)
noaa_api_token = 'Insert Key'

# Function to clean and prepare keywords
def clean_keywords(text):
    if pd.isna(text):
        return ""
    # Remove text within parentheses
    text = re.sub(r'\(.*?\)', '', text).strip()
    return text

# Function to create variations of the winery name
def create_winery_variations(winery):
    variations = ["Wines", "Wine", "Vineyard", "Estate", "Winery", "Vineyards"]
    return [f"{winery} {variation}" for variation in variations] + [winery]

# Function to construct search query
def construct_query(row, winery_variations):
    regions = [clean_keywords(row['Region 1']), clean_keywords(row['Region 2']), clean_keywords(row['Region 3'])]
    country = clean_keywords(row['Country'])

    # Construct different combinations
    combinations = []
    for winery_variation in winery_variations:
        for i in range(len(regions)):
            for j in range(i, len(regions)):
                query_parts = [winery_variation] + regions[i:j+1] + [country]
                combinations.append(' '.join(filter(None, query_parts)))

    return combinations, regions, country

# Function to calculate the bounding box
def get_gps_bounding_box(latitude, longitude, deg_lat=1.0, deg_lon=1.0):
    n = min(90, latitude + deg_lat)
    s = max(-90, latitude - deg_lat)
    e = min(180, longitude + deg_lon)
    w = max(-180, longitude - deg_lon)
    return n, w, s, e

# Function to find weather stations by bounding box with rate limiting
def get_stations_by_bounding_box(lat, lon, api_token):
    global noaa_request_count
    if noaa_request_count >= NOAA_DAILY_LIMIT:
        print("NOAA daily request limit reached.")
        return []

    time.sleep(NOAA_RATE_LIMIT)
    n, w, s, e = get_gps_bounding_box(lat, lon)
    url = f"https://www.ncei.noaa.gov/access/services/search/v1/data?dataset=global-summary-of-the-month&boundingBox={n},{w},{s},{e}&dataTypes=TMIN,TMAX,PRCP,TAVG&limit=10&offset=0"
    headers = {'token': api_token}
    try:
        response = requests.get(url, headers=headers, timeout=10)  # 10 seconds timeout
        noaa_request_count += 1
        if response.status_code == 200:
            stations_data = response.json().get('results', [])
            valid_stations = []
            for station in stations_data:
                station_id = station['id']
                # Extract the valid part of the station ID
                valid_station_id = station_id.split(':')[1].split('.')[0]
                valid_stations.append(valid_station_id)
            return valid_stations
    except requests.exceptions.Timeout:
        print("NOAA request timed out.")
    except Exception as e:
        print(f"Error in NOAA request: {e}")
    return []

# Function to check if address matches the country
def is_country_match(country, address):
    return country.lower() in address.lower()

# Function to check if address matches any of the regions and country
def is_region_country_match(regions, country, address):
    region_country_text = " ".join([r for r in regions if r] + [country]).lower()
    return any(region.lower() in address.lower() for region in region_country_text.split()) and country.lower() in address.lower()

# Function to search using Bing Maps API
def search_address(query):
    url = f"http://dev.virtualearth.net/REST/v1/Locations?query={query}&key={bing_maps_key}"
    response = requests.get(url)
    if response.status_code == 200:
        return response.json()
    return None

# Function to get monthly climate data for a station with rate limiting
def get_mly_climate_data_for_station(station_id, vintage_year, api_token):
    global noaa_request_count
    if noaa_request_count >= NOAA_DAILY_LIMIT:
        print("NOAA daily request limit reached.")
        return {}

    start_date = f"{vintage_year}-01-01"
    end_date = f"{vintage_year}-12-31"
    time.sleep(NOAA_RATE_LIMIT)
    url = f"https://www.ncei.noaa.gov/access/services/data/v1?dataset=global-summary-of-the-month&dataTypes=TMIN,TMAX,PRCP,TAVG&stations={station_id}&startDate={start_date}&endDate={end_date}&format=json&units=standard&includeAttributes=false"
    headers = {'token': api_token}

    try:
        response = requests.get(url, headers=headers, timeout=10)
        noaa_request_count += 1

        if response.status_code == 200:
            monthly_data_raw = response.json()
            monthly_data = {f"{data_type}_{month}": [] for data_type in ['TMIN', 'TMAX', 'PRCP', 'TAVG'] for month in range(1, 13)}

            for record in monthly_data_raw:
                month = int(record['DATE'].split('-')[1])
                for data_type in ['TMIN', 'TMAX', 'PRCP', 'TAVG']:
                    if record.get(data_type) is not None:
                        monthly_data[f"{data_type}_{month}"].append(float(record[data_type]))

            # Averaging the data
            averaged_data = {key: sum(values) / len(values) if values else None for key, values in monthly_data.items()}
            return averaged_data

    except requests.exceptions.Timeout:
        print("NOAA request timed out.")
    except Exception as e:
        print(f"Error in NOAA request: {e}")
    return {}

# Function to extract address, location name, and geocoordinates from the result
def extract_address_info(result):
    if result and 'resourceSets' in result:
        resources = result['resourceSets'][0]['resources']
        if resources:
            location_name = resources[0]['name']
            address = resources[0]['address']['formattedAddress']
            coordinates = resources[0]['point']['coordinates'] if 'point' in resources[0] else None
            return location_name, address, coordinates
    return None, None, None

# Function to check if the winery name is part of the business name in the location
def is_correct_business_match(winery_variations, location_name, address, country):
    return any(winery_variation.lower() in location_name.lower() for winery_variation in winery_variations) and is_country_match(country, address)

# Function to find the best match for the winery
def find_best_match(queries, winery_variations, regions, country):
    best_match = None
    for query in queries:
        result = search_address(query)
        location_name, address, coordinates = extract_address_info(result)
        if location_name and address and coordinates:
            if is_correct_business_match(winery_variations, location_name, address, country):
                return (query, location_name, address, coordinates)
            elif is_region_country_match(regions, country, address) and not best_match:
                best_match = (query, location_name, address, coordinates)

    return best_match

# Function to process each wine entry
def process_wine_entry(row):
    winery = clean_keywords(row['Winery'])
    winery_variations = create_winery_variations(winery)
    queries, regions, country = construct_query(row, winery_variations)

    best_match = find_best_match(queries, winery_variations, regions, country)
    if best_match:
        query, location_name, address, coordinates = best_match
        lat, lon = coordinates
        station_results = get_stations_by_bounding_box(lat, lon, noaa_api_token)

        aggregated_weather_data = {
            "TMAX": defaultdict(list),
            "TMIN": defaultdict(list),
            "PRCP": defaultdict(list),
            "TAVG": defaultdict(list)
        }

        for station_id in station_results:
            station_weather_data = get_mly_climate_data_for_station(station_id, row['Vintage'], noaa_api_token)
            if station_weather_data:
                for key, value in station_weather_data.items():
                    if value is not None:
                        metric, month = key.split('_')
                        aggregated_weather_data[metric][int(month)].append(value)

        averaged_weather_data = {}
        for metric, monthly_values in aggregated_weather_data.items():
            for month in range(1, 13):
                if monthly_values[month]:
                    avg_value = sum(monthly_values[month]) / len(monthly_values[month])
                    averaged_weather_data[f"{metric}_{month}"] = avg_value
                else:
                    averaged_weather_data[f"{metric}_{month}"] = None

        return {
            "Winery": row['Winery'],
            "Wine Name": row['Wine Name'],
            "Vintage": row['Vintage'],
            "Location Name": location_name,
            "Address": address,
            "Latitude": lat,
            "Longitude": lon,
            **averaged_weather_data
        }
    else:
        print(f"No valid address found for {row['Winery']}")
        return None

# Read CSV file
wine_data = pd.read_csv('data/clean/cleaned_combined_wine_data.csv')

# Process each wine entry
processed_wine_data = []
for _, row in wine_data.iterrows():
    processed_data = process_wine_entry(row)
    if processed_data:
        processed_wine_data.append(processed_data)

# Convert the list of dictionaries to a DataFrame
weather_enhanced_wine_data = pd.DataFrame(processed_wine_data)

# Save the results
weather_enhanced_wine_data.to_csv('data/intermediate/weather_enhanced_wine_data.csv', index=False)

# Display the results
weather_enhanced_wine_data.head()

NOAA request timed out.
NOAA request timed out.
No valid address found for Wiese & Krohn
NOAA request timed out.
No valid address found for W. & J. Graham's
No valid address found for Wiese & Krohn
No valid address found for Wiese & Krohn
No valid address found for W. & J. Graham's
No valid address found for W. & J. Graham's
NOAA request timed out.
NOAA request timed out.
NOAA request timed out.
NOAA request timed out.
NOAA request timed out.
NOAA request timed out.
No valid address found for Wiese & Krohn
No valid address found for Wiese & Krohn
No valid address found for Sebastiani
NOAA request timed out.
No valid address found for Sebastiani
No valid address found for Sebastiani
No valid address found for Heidsieck & Co Monopole
No valid address found for Heidsieck & Co Monopole
No valid address found for Argyle
No valid address found for Heidsieck & Co Monopole
NOAA request timed out.
No valid address found for Wellington
NOAA request timed out.
NOAA request timed out.
No valid add

In [147]:
test_data = pd.read_csv('data/intermediate/weather_enhanced_wine_data_sample.csv')
test_data

Winery                                          Wine Name  \
0              Calem              Calem 1961 Colheita Tawny Port (Port)   
1              Calem                  Calem 1961 Colheita Tawny  (Port)   
2            Warre's             Warre's 1961 Reserve Tawny Port (Port)   
3     Cossart Gordon                 Cossart Gordon 1962 Bual (Madeira)   
4        Van Zellers  Van Zellers 1962 Palmer Colheita White Port (P...   
..               ...                                                ...   
185            Salon  Salon 1990 Le Mesnil Blanc de Blancs Brut Char...   
186   Howard's Folly  Howard's Folly 1991 Casa Manoel Boullush White...   
187  Moulin Touchais  Moulin Touchais 1991 Chenin Blanc (Coteaux du ...   
188       Montecillo  Montecillo 1991 Seleccion Especial Gran Reserv...   
189         Blandy's            Blandy's 1991 Malmsey Malmsey (Madeira)   

     Vintage                                Location Name  \
0       1961                                     Portugal   
1       1961                                     Portugal   
2       1961                                     Portugal   
3       1962                                     Portugal   
4       1962                                     Portugal   
..       ...                                          ...   
185     1990  Salon-de-Provence, Bouches-du-Rhône, France   
186     1991                                     Portugal   
187     1991         Loire Valley, Indre-et-Loire, France   
188     1991                 Montecillo, Cantabria, Spain   
189     1991                                     Portugal   

                                         Address   Latitude  Longitude  \
0                                       Portugal  39.682198  -7.968288   
1                                       Portugal  39.682198  -7.968288   
2                                       Portugal  39.682198  -7.968288   
3                                       Portugal  39.682198  -7.968288   
4                                       Portugal  39.682198  -7.968288   
..                                           ...        ...        ...   
185  Salon-de-Provence, Bouches-du-Rhône, France  43.640297   5.086390   
186                                     Portugal  39.682198  -7.968288   
187         Loire Valley, Indre-et-Loire, France  47.398888   0.702778   
188                 Montecillo, Cantabria, Spain  42.774986  -3.975144   
189                                     Portugal  39.682198  -7.968288   

        TMAX_1     TMAX_2     TMAX_3  ...     TAVG_3     TAVG_4     TAVG_5  \
0    33.366667  43.200000  51.133333  ...  41.166667  44.566667  55.766667   
1    36.975000  47.466667  54.350000  ...  44.050000  46.825000  57.875000   
2    36.975000  47.466667  54.350000  ...  44.050000  46.825000  57.875000   
3    37.066667  39.875000  47.700000  ...  39.200000  51.175000  66.425000   
4    37.066667  39.875000  47.700000  ...  39.200000  51.175000  66.425000   
..         ...        ...        ...  ...        ...        ...        ...   
185  44.087500  43.911111  51.377778  ...  41.055556  49.644444  57.144444   
186  32.622222  44.622222  51.066667  ...  40.522222  51.766667  63.700000   
187  32.622222  44.622222  51.066667  ...  40.522222  51.766667  63.700000   
188  32.622222  44.622222  51.066667  ...  40.522222  51.766667  63.700000   
189  32.622222  44.622222  51.066667  ...  40.522222  51.766667  63.700000   

        TAVG_6     TAVG_7     TAVG_8     TAVG_9    TAVG_10    TAVG_11  \
0    68.633333  72.833333  73.800000  64.900000  53.433333  39.066667   
1    69.650000  74.025000  74.475000  66.975000  54.825000  42.400000   
2    69.650000  74.025000  74.475000  66.975000  54.825000  42.400000   
3    70.025000  72.275000  73.425000  63.825000  57.425000  42.350000   
4    70.025000  72.275000  73.425000  63.825000  57.425000  42.350000   
..         ...        ...        ...        ...        ...        ...   
185  69.077778  72.777778  71.755556  65.71

From the previous test we can see that the script works to some extent. Now we add a few more logic to the script, such as making it auto-save whenever an error occurs, double checking for duplicates if the script is ran multiple times, and have capacity to have more than one API key so the whole csv file can be iterated through within a reasonable time.

In [ ]:
# Constants for NOAA API rate limiting
NOAA_RATE_LIMIT = 0.2  # Seconds between requests
NOAA_DAILY_LIMIT = 10000  # Daily request limit per NOAA API token
noaa_request_count = 0  # Initialize NOAA request count

# List of NOAA API tokens
noaa_api_tokens = [
    'Key1',
    'Key2',
    'Key3'
]
current_noaa_token_index = 0  # Current NOAA API token index

# Annual limit for Bing Maps API transactions
BING_MAPS_ANNUAL_LIMIT = 125000

# List of Bing Maps API tokens and their transaction counts
bing_maps_keys_info = [
    {'key': 'Key1', 'transactions': 0}
]
current_bing_key_index = 0  # Current Bing Maps API token index

# Function to get the current NOAA API token
def get_current_noaa_api_token():
    return noaa_api_tokens[current_noaa_token_index]

# Function to increment the NOAA token index
def increment_noaa_token_index():
    global current_noaa_token_index
    current_noaa_token_index += 1
    if current_noaa_token_index >= len(noaa_api_tokens):
        print("All NOAA API tokens have reached their daily limit.")
        return False
    return True

# Function to get the current Bing Maps API key
def get_current_bing_maps_key():
    return bing_maps_keys_info[current_bing_key_index]['key']

# Function to increment the Bing Maps key index
def increment_bing_key_index():
    global current_bing_key_index
    current_bing_key_index += 1
    if current_bing_key_index >= len(bing_maps_keys_info):
        print("All Bing Maps API tokens have reached their annual limit.")
        return False
    return True

# Function to check and update Bing Maps transactions
def check_and_update_bing_transactions():
    global current_bing_key_index
    if bing_maps_keys_info[current_bing_key_index]['transactions'] >= BING_MAPS_ANNUAL_LIMIT:
        if not increment_bing_key_index():
            return False
    bing_maps_keys_info[current_bing_key_index]['transactions'] += 1
    return True

# Function to clean and prepare keywords
def clean_keywords(text):
    if pd.isna(text):
        return ""
    # Remove text within parentheses
    text = re.sub(r'\(.*?\)', '', text).strip()
    return text

# Function to create variations of the winery name
def create_winery_variations(winery):
    variations = ["Wines", "Wine", "Vineyard", "Estate", "Winery", "Vineyards", "Cellars", "Cellar"]
    return [f"{winery} {variation}" for variation in variations] + [winery]

# Function to construct search query
def construct_query(row, winery_variations):
    regions = [clean_keywords(row['Region 1']), clean_keywords(row['Region 2']), clean_keywords(row['Region 3'])]
    country = clean_keywords(row['Country'])

    # Construct different combinations
    combinations = []
    for winery_variation in winery_variations:
        for i in range(len(regions)):
            for j in range(i, len(regions)):
                query_parts = [winery_variation] + regions[i:j+1] + [country]
                combinations.append(' '.join(filter(None, query_parts)))

    return combinations, regions, country

# Function to check if the winery name is part of the business name in the location
def is_correct_business_match(winery_variations, location_name, address, country):
    return any(winery_variation.lower() in location_name.lower() for winery_variation in winery_variations) and is_country_match(country, address)

# Function to calculate the bounding box
def get_gps_bounding_box(latitude, longitude, deg_lat=1.0, deg_lon=1.0):
    n = min(90, latitude + deg_lat)
    s = max(-90, latitude - deg_lat)
    e = min(180, longitude + deg_lon)
    w = max(-180, longitude - deg_lon)
    return n, w, s, e

# Function to find weather stations by bounding box with rate limiting
def get_stations_by_bounding_box(lat, lon):
    global noaa_request_count
    if noaa_request_count >= NOAA_DAILY_LIMIT:
        if not increment_noaa_token_index():
            return []  # All NOAA tokens exhausted
        noaa_request_count = 0  # Reset request count for new token

    api_token = get_current_noaa_api_token()
    time.sleep(NOAA_RATE_LIMIT)
    n, w, s, e = get_gps_bounding_box(lat, lon)
    url = f"https://www.ncei.noaa.gov/access/services/search/v1/data?dataset=global-summary-of-the-month&boundingBox={n},{w},{s},{e}&dataTypes=TMIN,TMAX,PRCP,TAVG&limit=10&offset=0"
    headers = {'token': api_token}
    try:
        response = requests.get(url, headers=headers, timeout=10)
        noaa_request_count += 1
        if response.status_code == 200:
            stations_data = response.json().get('results', [])
            valid_stations = [station['id'].split(':')[1].split('.')[0] for station in stations_data]
            return valid_stations
    except requests.exceptions.Timeout:
        print("NOAA request timed out.")
        save_progress(processed_wine_data)  # Save progress on error
    except Exception as e:
        print(f"Error in NOAA request: {e}")
        save_progress(processed_wine_data)  # Save progress on error
    return []

# Function to get monthly climate data for a station with rate limiting
def get_mly_climate_data_for_station(station_id, vintage_year):
    global noaa_request_count
    if noaa_request_count >= NOAA_DAILY_LIMIT:
        if not increment_noaa_token_index():
            return {}  # All NOAA tokens exhausted
        noaa_request_count = 0  # Reset request count for new token

    api_token = get_current_noaa_api_token()
    time.sleep(NOAA_RATE_LIMIT)
    url = f"https://www.ncei.noaa.gov/access/services/data/v1?dataset=global-summary-of-the-month&dataTypes=TMIN,TMAX,PRCP,TAVG&stations={station_id}&startDate={vintage_year}-01-01&endDate={vintage_year}-12-31&format=json&units=standard&includeAttributes=false"
    headers = {'token': api_token}
    try:
        response = requests.get(url, headers=headers, timeout=10)
        noaa_request_count += 1
        if response.status_code == 200:
            monthly_data_raw = response.json()
            monthly_data = {f"{data_type}_{month}": [] for data_type in ['TMIN', 'TMAX', 'PRCP', 'TAVG'] for month in range(1, 13)}

            for record in monthly_data_raw:
                month = int(record['DATE'].split('-')[1])
                for data_type in ['TMIN', 'TMAX', 'PRCP', 'TAVG']:
                    if record.get(data_type) is not None:
                        monthly_data[f"{data_type}_{month}"].append(float(record[data_type]))
            # Averaging the data
            processed_data = {key: sum(values) / len(values) if values else None for key, values in monthly_data.items()}
            return processed_data
    except requests.exceptions.Timeout:
        print("NOAA request timed out.")
        save_progress(processed_wine_data)  # Save progress on error
    except Exception as e:
        print(f"Error in NOAA request: {e}")
        save_progress(processed_wine_data)  # Save progress on error
    return {}

# Function to search using Bing Maps API
def search_address(query):
    if not check_and_update_bing_transactions():
        return None  # All Bing Maps keys exhausted or reached limit

    key = get_current_bing_maps_key()
    url = f"http://dev.virtualearth.net/REST/v1/Locations?query={query}&key={key}"
    try:
        response = requests.get(url)
        if response.status_code == 200:
            return response.json()
        elif response.status_code == 401:  # Assuming 401 indicates a key limit
            if increment_bing_key_index():
                return search_address(query)  # Retry with the next key
    except requests.RequestException as e:
        print(f"Request failed: {e}")
        save_progress(processed_wine_data)  # Save progress on error
    return None

# Additional helper functions (e.g., is_country_match, is_region_country_match, extract_address_info)
def is_country_match(country, address):
    return country.lower() in address.lower()

def is_region_country_match(regions, country, address):
    address_lower = address.lower()
    return any(region.lower() in address_lower for region in regions if region) and country.lower() in address_lower

def extract_address_info(result):
    if result and 'resourceSets' in result and result['resourceSets']:
        resources = result['resourceSets'][0]['resources']
        if resources:
            location_name = resources[0].get('name', '')
            address = resources[0]['address'].get('formattedAddress', '')
            coordinates = resources[0]['point']['coordinates'] if 'point' in resources[0] else None
            return location_name, address, coordinates
    return None, None, None

# Function to append data to CSV
def append_to_csv(dataframe, filepath):
    if not dataframe.empty:
        dataframe.to_csv(filepath, mode='a', header=not os.path.exists(filepath), index=False)
        print("Data appended to:", filepath)

# Function to save progress whenever an error occurs
def save_progress(processed_data, filepath='data/intermediate/weather_enhanced_wine_data.csv'):
    if isinstance(filepath, str):  # Check if filepath is a string
        current_data_df = pd.DataFrame(processed_data)
        append_to_csv(current_data_df, filepath)
    else:
        raise ValueError("Invalid filepath. Filepath must be a string.")

# Add a cache for coordinates
coordinates_cache = {}

def get_cache_key(winery, country, regions):
    # Create a composite key based on winery, country, and non-empty regions
    non_empty_regions = [region for region in regions if region]
    return f"{winery}|{country}|{'|'.join(non_empty_regions)}"

def cache_coordinates(key, coordinates):
    coordinates_cache[key] = coordinates

def get_cached_coordinates(key):
    return coordinates_cache.get(key)    

# Function to process each wine entry with error handling and coordinate caching
def process_wine_entry(row):
    try:
        winery = clean_keywords(row['Winery'])
        winery_variations = create_winery_variations(winery)
        queries, regions, country = construct_query(row, winery_variations)

        # Check if coordinates are already cached
        cache_key = get_cache_key(winery, country, regions)
        cached_coordinates = get_cached_coordinates(cache_key)

        if cached_coordinates:
            lat, lon = cached_coordinates
            station_results = get_stations_by_bounding_box(lat, lon)
            if station_results:
                aggregated_weather_data = defaultdict(list)
                for station_id in station_results:
                    station_weather_data = get_mly_climate_data_for_station(station_id, row['Vintage'])
                    for key, value in station_weather_data.items():
                        if value is not None:  # Only append if value is not None
                            aggregated_weather_data[key].append(value)
                averaged_weather_data = {k: sum(v)/len(v) for k, v in aggregated_weather_data.items() if v}
                return {
                    "Winery": row['Winery'],
                    "Wine Name": row['Wine Name'],
                    "Vintage": row['Vintage'],
                    "Latitude": lat,
                    "Longitude": lon,
                    **averaged_weather_data
                }

        for query in queries:
            result = search_address(query)
            location_name, address, coordinates = extract_address_info(result)
            if location_name and address and coordinates:
                # Cache the new coordinates
                cache_coordinates(cache_key, coordinates)
                
                lat, lon = coordinates
                station_results = get_stations_by_bounding_box(lat, lon)
                if station_results:
                    aggregated_weather_data = defaultdict(list)
                    for station_id in station_results:
                        station_weather_data = get_mly_climate_data_for_station(station_id, row['Vintage'])
                        for key, value in station_weather_data.items():
                            if value is not None:  # Only append if value is not None
                                aggregated_weather_data[key].append(value)
                    averaged_weather_data = {k: sum(v)/len(v) for k, v in aggregated_weather_data.items() if v}
                    return {
                        "Winery": row['Winery'],
                        "Wine Name": row['Wine Name'],
                        "Vintage": row['Vintage'],
                        "Location Name": location_name,
                        "Address": address,
                        "Latitude": lat,
                        "Longitude": lon,
                        **averaged_weather_data
                    }

        print(f"No valid address found for {row['Winery']}")
        return None
    except Exception as e:
        print(f"Error processing {row['Winery']}: {e}")
        save_progress(processed_wine_data)  # Save progress on error

# Main script execution
intermediate_file_path = 'data/intermediate/weather_enhanced_wine_data.csv'

# Read existing data if available
if os.path.exists(intermediate_file_path):
    processed_wine_data_df = pd.read_csv(intermediate_file_path)
else:
    processed_wine_data_df = pd.DataFrame()

# Read the main wine data
wine_data = pd.read_csv('data/clean/cleaned_combined_wine_data.csv')

# Filter out already processed wines
processed_wine_names = set(processed_wine_data_df['Wine Name'])
wine_data = wine_data[~wine_data['Wine Name'].isin(processed_wine_names)]

# Initialize a list to track new processed data
new_processed_wine_data = []

# Process each wine entry
for _, row in wine_data.iterrows():
    processed_data = process_wine_entry(row)
    if processed_data:
        processed_wine_data.append(processed_data)
        new_processed_wine_data.append(processed_data)  # Add to new data list

# Convert the new processed data to a DataFrame
new_processed_data_df = pd.DataFrame(new_processed_wine_data)

# Append new data to the intermediate file
append_to_csv(new_processed_data_df, intermediate_file_path)

# Clear the list of new processed data after appending
new_processed_wine_data.clear()

# Display the results
new_processed_data_df.head()

No valid address found for Wiese & Krohn
No valid address found for W. & J. Graham's
No valid address found for Wiese & Krohn
No valid address found for Wiese & Krohn
No valid address found for W. & J. Graham's
No valid address found for W. & J. Graham's
No valid address found for Wiese & Krohn
No valid address found for Wiese & Krohn
No valid address found for Sebastiani
No valid address found for Sebastiani
No valid address found for Sebastiani
No valid address found for Heidsieck & Co Monopole
No valid address found for Heidsieck & Co Monopole
No valid address found for Argyle
No valid address found for Heidsieck & Co Monopole
No valid address found for Wellington
No valid address found for Gan Eden
No valid address found for Argyle
No valid address found for Gloria Ferrer
No valid address found for Sebastiani
No valid address found for Fortino
No valid address found for Iron Horse
NOAA request timed out.
Data appended to: data/intermediate/weather_enhanced_wine_data.csv
NOAA reques

No valid address found for Broadbent
No valid address found for Iron Horse
NOAA request timed out.
Data appended to: data/intermediate/weather_enhanced_wine_data.csv
No valid address found for Mumm Cuvee Napa
No valid address found for Vigna Piccola
No valid address found for Agrapart & Fils
NOAA request timed out.
Data appended to: data/intermediate/weather_enhanced_wine_data.csv
No valid address found for Duck Pond
NOAA request timed out.
Data appended to: data/intermediate/weather_enhanced_wine_data.csv
No valid address found for Kollwentz
No valid address found for Stellenryck
No valid address found for Pellegrini Vineyards
No valid address found for Domaine Carneros
No valid address found for Glenora
No valid address found for Bruno Giacosa
No valid address found for Iron Horse
No valid address found for Kunde
No valid address found for Moet & Chandon
No valid address found for Roederer Estate
No valid address found for Columbia Crest
No valid address found for Bodegas Corral
No v

With rate limit hit and the fact that we currently have enough data to do some preliminary data exploration, we can continue to the next steps for now.

## Combining Original Data with API Data To Prepare for Preliminary EDA

First let's combine the wine data that have matching downloaded weather data.

In [3]:
# Load Data
filtered_wine_data = pd.read_csv(r'data\clean\filtered_wine_data.csv')
downloaded_weather_data = pd.read_csv('data\clean\merged_weather.csv')

# Sanity Check
filtered_wine_data.head(10)

Wine Name      Region 1  \
0  Bodegas Dios Baco S.L. NV 1970 Oxford Pedro Xi...     Andalucia   
1           Adega de Favaios 1980  Moscatel do Douro           NaN   
2  Adega de Favaios 1980 Moscatel (Moscatel do Do...           NaN   
3          Cuva Vella 1980 Vintage Muscat (Valencia)       Levante   
4  Moulin Touchais 1982 Chenin Blanc (Coteaux du ...  Loire Valley   
5  Moulin Touchais 1985 Chenin Blanc (Coteaux du ...  Loire Valley   
6  Bodegas Hidalgo 1986 Oloroso Single Vintage Si...         Jerez   
7  Astoria NV 1987 Anniversario 2009 Dry Prosecco...        Veneto   
8  Moulin Touchais 1991 Chenin Blanc (Coteaux du ...  Loire Valley   
9  KWV 1993 Late Bottled Vintage Port (Western Cape)           NaN   

            Region 2                Region 3       Country  Score  Price  \
0                NaN                   Jerez         Spain     85   40.0   
1  Moscatel do Douro                     NaN      Portugal     93  137.0   
2  Moscatel do Douro                     NaN      Portugal     93  137.0   
3                NaN                Valencia         Spain     90   65.0   
4                NaN        Coteaux du Layon        France     95   64.0   
5                NaN        Coteaux du Layon        France     94   72.0   
6          Andalucia                     NaN         Spain     92  155.0   
7                NaN  Prosecco di Conegliano         Italy     87   24.0   
8                NaN        Coteaux du Layon        France     92   72.0   
9       Western Cape                     NaN  South Africa     88   15.0   

                   Winery       Variety  Vintage  
0  Bodegas Dios Baco S.L.        Sherry     1970  
1        Adega de Favaios      Moscatel     1980  
2        Adega de Favaios        Muscat     1980  
3              Cuva Vella        Muscat     1980  
4         Moulin Touchais  Chenin Blanc     1982  
5         Moulin Touchais  Chenin Blanc     1985  
6         Bodegas Hidalgo        Sherry     1986  
7                 Astoria     Sparkling     1987  
8         Moulin Touchais  Chenin Blanc     1991  
9                     KWV    Port Blend     1993

In [4]:
downloaded_weather_data.head(10)

Station ID      Country                        City  Year  daily_temp_Jan  \
0           0    AUSTRALIA  SCONE SOIL CONS          0  1985            24.6   
1           0    AUSTRALIA  SCONE SOIL CONS          0  1987            25.7   
2        6600  SWITZERLAND              ST. CHRISCHONA  2004             0.9   
3        6601  SWITZERLAND           BASEL / BINNINGEN  2004             2.3   
4        6601  SWITZERLAND           BASEL / BINNINGEN  2011             2.4   
5        6601  SWITZERLAND           BASEL / BINNINGEN  2012             3.8   
6        6602  SWITZERLAND                    DELEMONT  2004             1.7   
7        6602  SWITZERLAND                    DELEMONT  2012             3.0   
8        6604  SWITZERLAND                   NEUCHATEL  2004             1.9   
9        6604  SWITZERLAND                   NEUCHATEL  2011             1.9   

   daily_temp_Feb  daily_temp_Mar  daily_temp_Apr  daily_temp_May  \
0            22.4            21.5            17.7            14.2   
1            24.7            19.6            17.9            14.2   
2             2.3             4.8             9.5            11.7   
3             3.0             5.7            10.6            13.2   
4             3.9             7.5            13.4            16.6   
5            -2.2             8.9             9.8            15.5   
6             1.5             3.9             9.4            12.2   
7            -4.0             7.7             9.5            14.7   
8             3.0             4.8            10.0            13.1   
9             3.3             7.4            13.6            16.1   

   daily_temp_Jun  ...  humidity_Mar  humidity_Apr  humidity_May  \
0            10.2  ...           NaN           NaN           NaN   
1            12.0  ...           NaN           NaN           NaN   
2            15.7  ...           NaN           NaN           NaN   
3            17.7  ...           NaN           NaN           NaN   
4            18.1  ...           NaN           NaN           NaN   
5            18.4  ...           NaN           NaN           NaN   
6            16.6  ...           NaN           NaN           NaN   
7            18.0  ...           6.9           7.6           7.1   
8            17.4  ...           NaN           NaN           NaN   
9            17.5  ...           NaN           NaN           NaN   

   humidity_Jun  humidity_Jul  humidity_Aug  humidity_Sep  humidity_Oct  \
0           NaN           NaN           NaN           NaN           NaN   
1           NaN           NaN           NaN           NaN           NaN   
2           NaN           NaN           NaN           NaN           NaN   
3           NaN           NaN           NaN           NaN           NaN   
4           NaN           NaN           NaN           NaN           NaN   
5           NaN           NaN           NaN           NaN           NaN   
6           NaN           NaN           NaN           NaN           NaN   
7           7.4           7.4           7.2           8.6           9.0   
8           NaN           NaN           NaN           NaN           NaN   
9           NaN           NaN           NaN           NaN           NaN   

   humidity_Nov  humidity_Dec  
0           NaN           NaN  
1           NaN           NaN  
2           NaN           NaN  
3           NaN           NaN  
4           NaN           NaN  
5           NaN           NaN  
6           NaN           NaN  
7           9.2           8.7  
8           NaN           NaN  
9           NaN           NaN  

[10 rows x 64 columns]

In [9]:
# Ensure the data types are consistent for merging
filtered_wine_data['Vintage'] = filtered_wine_data['Vintage'].astype(int)
downloaded_weather_data['Year'] = downloaded_weather_data['Year'].astype(int)

# Ensure country names are consistent
filtered_wine_data['Country'] = filtered_wine_data['Country'].str.strip().str.lower()
downloaded_weather_data['Country'] = downloaded_weather_data['Country'].str.strip().str.lower()

# Create a function to check region-city matching
def region_city_match(wine_row, weather_df):
    for region in ['Region 1', 'Region 2', 'Region 3']:
        region_value = wine_row[region]
        if pd.notna(region_value):
            region_value = region_value.lower()
            for _, weather_row in weather_df.iterrows():
                city = weather_row['City'].lower()
                if region_value in city:
                    return weather_row
    return None

# Apply the function and create a temporary DataFrame for merged results
temp_df = pd.DataFrame()
for _, wine_row in filtered_wine_data.iterrows():
    matching_weather_row = region_city_match(wine_row, downloaded_weather_data)
    if matching_weather_row is not None:
        combined_row = {**wine_row, **matching_weather_row}
        temp_df = pd.concat([temp_df, pd.DataFrame([combined_row])], ignore_index=True)

# Merge the dataframes on 'Country' and 'Vintage/Year'
merged_df = pd.merge(filtered_wine_data, temp_df, left_on=['Country', 'Vintage'], right_on=['Country', 'Year'], how='inner')

# Drop unnecessary columns
merged_df.drop(['Station ID', 'City', 'Year'], axis=1, inplace=True)

# Save the merged dataframe
merged_df.to_csv('data\intermediate\merged_data.csv', index=False)

# Check Results
merged_df

Wine Name_x Region 1_x  \
0      Bodegas Dios Baco S.L. NV 1970 Oxford Pedro Xi...  Andalucia   
1      Bodegas Dios Baco S.L. NV 1970 Oxford Pedro Xi...  Andalucia   
2      Bodegas Dios Baco S.L. NV 1970 Oxford Pedro Xi...  Andalucia   
3      Bodegas Dios Baco S.L. NV 1970 Oxford Pedro Xi...  Andalucia   
4      Bodegas Dios Baco S.L. NV 1970 Oxford Pedro Xi...  Andalucia   
...                                                  ...        ...   
22717  Don Tony Perez 2014 Gran Reserva Cabernet Sauv...        NaN   
22718  Don Tony Perez 2014 Gran Reserva Cabernet Sauv...        NaN   
22719  Don Tony Perez 2014 Gran Reserva Cabernet Sauv...        NaN   
22720  Don Tony Perez 2014 Gran Reserva Cabernet Sauv...        NaN   
22721  Don Tony Perez 2014 Gran Reserva Cabernet Sauv...        NaN   

          Region 2_x Region 3_x Country  Score_x  Price_x  \
0                NaN      Jerez   spain       85     40.0   
1                NaN      Jerez   spain       85     40.0   
2                NaN      Jerez   spain       85     40.0   
3                NaN      Jerez   spain       85     40.0   
4                NaN      Jerez   spain       85     40.0   
...              ...        ...     ...      ...      ...   
22717  Curico Valley        NaN   chile       88     19.0   
22718  Curico Valley        NaN   chile       88     19.0   
22719  Curico Valley        NaN   chile       88     19.0   
22720  Curico Valley        NaN   chile       88     19.0   
22721  Curico Valley        NaN   chile       88     19.0   

                     Winery_x           Variety_x  Vintage_x  ...  \
0      Bodegas Dios Baco S.L.              Sherry       1970  ...   
1      Bodegas Dios Baco S.L.              Sherry       1970  ...   
2      Bodegas Dios Baco S.L.              Sherry       1970  ...   
3      Bodegas Dios Baco S.L.              Sherry       1970  ...   
4      Bodegas Dios Baco S.L.              Sherry       1970  ...   
...                       ...                 ...        ...  ...   
22717          Don Tony Perez  Cabernet Sauvignon       2014  ...   
22718          Don Tony Perez  Cabernet Sauvignon       2014  ...   
22719          Don Tony Perez  Cabernet Sauvignon       2014  ...   
22720          Don Tony Perez  Cabernet Sauvignon       2014  ...   
22721          Don Tony Perez  Cabernet Sauvignon       2014  ...   

      humidity_Mar humidity_Apr humidity_May humidity_Jun  humidity_Jul  \
0              NaN          NaN          NaN          NaN           NaN   
1              NaN          NaN          NaN          NaN           NaN   
2              NaN          NaN          NaN          NaN           NaN   
3              NaN          NaN          NaN          NaN           NaN   
4              NaN          NaN          NaN          NaN           NaN   
...            ...          ...          ...          ...           ...   
22717          NaN          NaN          NaN          NaN           NaN   
22718          NaN          NaN          NaN          NaN           NaN   
22719          NaN          NaN          NaN          NaN           NaN   
22720          NaN          NaN          NaN          NaN           NaN   
22721          NaN          NaN          NaN          NaN           NaN   

       humidity_Aug humidity_Sep humidity_Oct  humidity_Nov  humidity_Dec  
0               NaN          NaN          NaN           NaN           NaN  
1               NaN          NaN          NaN           NaN           NaN  
2               NaN          NaN          NaN           NaN           NaN  
3               NaN          NaN          NaN           NaN           NaN  
4               NaN          NaN          NaN           NaN           NaN  
...             ...          ...          ...           ...           ...  
22717           NaN          NaN          NaN           NaN           NaN  
22718           NaN          NaN          NaN           NaN           NaN  
22719           NaN          NaN          NaN

In [10]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22722 entries, 0 to 22721
Data columns (total 79 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Wine Name_x         22722 non-null  object 
 1   Region 1_x          21399 non-null  object 
 2   Region 2_x          13406 non-null  object 
 3   Region 3_x          9316 non-null   object 
 4   Country             22722 non-null  object 
 5   Score_x             22722 non-null  int64  
 6   Price_x             19339 non-null  float64
 7   Winery_x            22722 non-null  object 
 8   Variety_x           22533 non-null  object 
 9   Vintage_x           22722 non-null  int32  
 10  Wine Name_y         22722 non-null  object 
 11  Region 1_y          18861 non-null  object 
 12  Region 2_y          20532 non-null  object 
 13  Region 3_y          2190 non-null   object 
 14  Score_y             22722 non-null  int64  
 15  Price_y             19226 non-null  float64
 16  Wine

In [11]:
filtered_wine_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16760 entries, 0 to 16759
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Wine Name  16760 non-null  object 
 1   Region 1   15110 non-null  object 
 2   Region 2   13048 non-null  object 
 3   Region 3   3686 non-null   object 
 4   Country    16760 non-null  object 
 5   Score      16760 non-null  int64  
 6   Price      15406 non-null  float64
 7   Winery     16760 non-null  object 
 8   Variety    16705 non-null  object 
 9   Vintage    16760 non-null  int32  
dtypes: float64(1), int32(1), int64(1), object(7)
memory usage: 1.2+ MB


Next, we will clean up the downloaded data that have been merged. We need to drop duplicates (which it likely there are some considering the original filtered_wine_data only have 16760 rows and we somehow ended up with 22722 rows in the merged data), drop humidity data (since we don't have that information available in the API data), drop rows that have null precipitation values, and as well as standardize the column names.

In [12]:
# Drop duplicate rows based on 'Wine Name_x'
merged_df.drop_duplicates(subset='Wine Name_x', keep='first', inplace=True)

# Drop humidity columns
humidity_cols = [col for col in merged_df.columns if 'humidity' in col]
merged_df.drop(humidity_cols, axis=1, inplace=True)

# Drop rows with null values in any of the precipitation columns
precipitation_cols = [col for col in merged_df.columns if 'precipitation' in col]
merged_df.dropna(subset=precipitation_cols, inplace=True)

# Capitalize the first letter of each country name
merged_df['Country'] = merged_df['Country'].str.capitalize()

# Remove '_x' and '_y' from column names
merged_df.columns = [col.replace('_x', '').replace('_y', '') for col in merged_df.columns]

# Reset the index
merged_df.reset_index(drop=True, inplace=True)

# Save the cleaned dataframe
merged_df.to_csv('data\intermediate\cleaned_merged_data.csv', index=False)

# Check the cleaned dataframe
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212 entries, 0 to 211
Data columns (total 67 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Wine Name           212 non-null    object 
 1   Region 1            211 non-null    object 
 2   Region 2            92 non-null     object 
 3   Region 3            120 non-null    object 
 4   Country             212 non-null    object 
 5   Score               212 non-null    int64  
 6   Price               171 non-null    float64
 7   Winery              212 non-null    object 
 8   Variety             209 non-null    object 
 9   Vintage             212 non-null    int32  
 10  Wine Name           212 non-null    object 
 11  Region 1            212 non-null    object 
 12  Region 2            210 non-null    object 
 13  Region 3            2 non-null      object 
 14  Score               212 non-null    int64  
 15  Price               212 non-null    float64
 16  Winery  

In [13]:
merged_df.head()

Wine Name   Region 1  \
0  Bodegas Dios Baco S.L. NV 1970 Oxford Pedro Xi...  Andalucia   
1            Bodega Norton 1999 Chardonnay (Mendoza)    Mendoza   
2  Domaine de la Courtade 2001 L'Alycastre Rose (...   Provence   
3  Chateau de Pourcieux 2001 Rose (Cotes de Prove...   Provence   
4  Commanderie de la Bargemone 2001 Rose (Coteaux...   Provence   

           Region 2                   Region 3    Country  Score  Price  \
0               NaN                      Jerez      Spain     85   40.0   
1  Mendoza Province                        NaN  Argentina     80    8.0   
2               NaN          Cotes de Provence     France     81   10.0   
3               NaN          Cotes de Provence     France     83    9.0   
4               NaN  Coteaux d'Aix-en-Provence     France     87   10.0   

                        Winery     Variety  Vintage  ... daily_temp_MIN_Mar  \
0       Bodegas Dios Baco S.L.      Sherry     1970  ...                NaN   
1                Bodega Norton  Chardonnay     1999  ...               15.4   
2       Domaine de la Courtade        Rose     2001  ...                6.5   
3         Chateau de Pourcieux        Rose     2001  ...                6.5   
4  Commanderie de la Bargemone        Rose     2001  ...                6.5   

  daily_temp_MIN_Apr daily_temp_MIN_May daily_temp_MIN_Jun  \
0                NaN                NaN                NaN   
1                9.1                7.5                3.2   
2                5.6               12.2               12.3   
3                5.6               12.2               12.3   
4                5.6               12.2               12.3   

   daily_temp_MIN_Jul  daily_temp_MIN_Aug daily_temp_MIN_Sep  \
0                 NaN                 NaN                NaN   
1                 0.9                 3.9                9.0   
2                15.5                15.7               10.0   
3                15.5                15.7               10.0   
4                15.5                15.7               10.0   

  daily_temp_MIN_Oct  daily_temp_MIN_Nov  daily_temp_MIN_Dec  
0                NaN                 NaN                 NaN  
1               12.0                14.3                16.6  
2               10.8                 1.5                -1.3  
3               10.8                 1.5                -1.3  
4               10.8                 1.5                -1.3  

[5 rows x 67 columns]

From this cleaning it is see that we still need to drop duplicate columns, and also our useable rows is significantly less than the result of filtered_wine_data, which shouldn't be the case. So we will need to try to make the merged weather data of the downloaded data again.

In [16]:
# Load Dataframes
wine_data = pd.read_csv('data/clean/cleaned_combined_wine_data.csv')
merged_weather_df = pd.read_csv('data/clean/merged_weather.csv')

# Select required weather columns
weather_columns = ['City', 'Country', 'daily_temp_Jan', 'daily_temp_Feb', 'daily_temp_Mar', 'daily_temp_Apr',
                   'daily_temp_May', 'daily_temp_Jun', 'daily_temp_Jul', 'daily_temp_Aug', 'daily_temp_Sep',
                   'daily_temp_Oct', 'daily_temp_Nov', 'daily_temp_Dec', 'precipitation_Jan', 'precipitation_Feb',
                   'precipitation_Mar', 'precipitation_Apr', 'precipitation_May', 'precipitation_Jun',
                   'precipitation_Jul', 'precipitation_Aug', 'precipitation_Sep', 'precipitation_Oct',
                   'precipitation_Nov', 'precipitation_Dec', 'daily_temp_MAX_Jan', 'daily_temp_MAX_Feb',
                   'daily_temp_MAX_Mar', 'daily_temp_MAX_Apr', 'daily_temp_MAX_May', 'daily_temp_MAX_Jun',
                   'daily_temp_MAX_Jul', 'daily_temp_MAX_Aug', 'daily_temp_MAX_Sep', 'daily_temp_MAX_Oct',
                   'daily_temp_MAX_Nov', 'daily_temp_MAX_Dec', 'daily_temp_MIN_Jan', 'daily_temp_MIN_Feb',
                   'daily_temp_MIN_Mar', 'daily_temp_MIN_Apr', 'daily_temp_MIN_May', 'daily_temp_MIN_Jun',
                   'daily_temp_MIN_Jul', 'daily_temp_MIN_Aug', 'daily_temp_MIN_Sep', 'daily_temp_MIN_Oct',
                   'daily_temp_MIN_Nov', 'daily_temp_MIN_Dec']

# Create a temporary DataFrame with unique city-country pairs
unique_city_country = merged_weather_df[['City', 'Country']].drop_duplicates()
unique_city_country['City'] = unique_city_country['City'].str.upper()
unique_city_country['City Words'] = unique_city_country['City'].apply(lambda x: x.split())

# Function to get matching weather data row
def get_matching_weather_data(row, city_country_df):
    for region_key in ['Region 1', 'Region 2', 'Region 3']:
        region = row[region_key]
        if pd.notna(region):
            region_words = set(region.upper().split())
            for _, city_country_row in city_country_df.iterrows():
                if any(word in region_words for word in city_country_row['City Words']) and row['Country'].upper() == city_country_row['Country'].upper():
                    # Match found, return relevant weather data
                    return merged_weather_df[merged_weather_df['City'] == city_country_row['City']].iloc[0][weather_columns]
    return None

# Ensure all relevant columns are strings and handle NaNs
wine_data[['Region 1', 'Region 2', 'Region 3']] = wine_data[['Region 1', 'Region 2', 'Region 3']].fillna('').astype(str)
wine_data['Country'] = wine_data['Country'].fillna('').astype(str)

# Merge weather data with wine_data
merged_rows = []
for _, row in wine_data.iterrows():
    weather_data_row = get_matching_weather_data(row, unique_city_country)
    if weather_data_row is not None:
        merged_row = {**row, **weather_data_row}
        merged_rows.append(merged_row)

# Create merged_df from the merged rows
merged_df = pd.DataFrame(merged_rows)

# Save merged_df
merged_df.to_csv('data/intermediate/merged_data_2.csv', index=False)

# Check result
merged_df.head()

Wine Name      Region 1  \
0  Bodegas Dios Baco S.L. NV 1970 Oxford Pedro Xi...     Andalucia   
1           Adega de Favaios 1980  Moscatel do Douro                 
2  Adega de Favaios 1980 Moscatel (Moscatel do Do...                 
3          Cuva Vella 1980 Vintage Muscat (Valencia)       Levante   
4  Moulin Touchais 1982 Chenin Blanc (Coteaux du ...  Loire Valley   

            Region 2          Region 3   Country  Score  Price  \
0                                Jerez     SPAIN     85   40.0   
1  Moscatel do Douro                    PORTUGAL     93  137.0   
2  Moscatel do Douro                    PORTUGAL     93  137.0   
3                             Valencia     SPAIN     90   65.0   
4                     Coteaux du Layon    FRANCE     95   64.0   

                   Winery       Variety  Vintage  ... daily_temp_MIN_Mar  \
0  Bodegas Dios Baco S.L.        Sherry     1970  ...                9.2   
1        Adega de Favaios      Moscatel     1980  ...                NaN   
2        Adega de Favaios        Muscat     1980  ...                NaN   
3              Cuva Vella        Muscat     1980  ...                8.6   
4         Moulin Touchais  Chenin Blanc     1982  ...                5.7   

   daily_temp_MIN_Apr  daily_temp_MIN_May  daily_temp_MIN_Jun  \
0                 9.8                11.6                16.5   
1                 NaN                 NaN                 NaN   
2                 NaN                 NaN                 NaN   
3                 8.4                 9.7                16.8   
4                 7.9                10.5                13.1   

   daily_temp_MIN_Jul  daily_temp_MIN_Aug  daily_temp_MIN_Sep  \
0                18.6                18.4                16.6   
1                 NaN                 NaN                 NaN   
2                 NaN                 NaN                 NaN   
3                20.4                21.1                19.1   
4                15.8                14.3                15.2   

   daily_temp_MIN_Oct  daily_temp_MIN_Nov  daily_temp_MIN_Dec  
0                14.3                10.4                 9.0  
1                 NaN                 NaN                 NaN  
2                 NaN                 NaN                 NaN  
3                11.6                 8.0                 6.6  
4                14.0                10.2                 8.0  

[5 rows x 59 columns]

In [17]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16760 entries, 0 to 16759
Data columns (total 59 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Wine Name           16760 non-null  object 
 1   Region 1            16760 non-null  object 
 2   Region 2            16760 non-null  object 
 3   Region 3            16760 non-null  object 
 4   Country             16760 non-null  object 
 5   Score               16760 non-null  int64  
 6   Price               15406 non-null  float64
 7   Winery              16760 non-null  object 
 8   Variety             16705 non-null  object 
 9   Vintage             16760 non-null  int64  
 10  City                16760 non-null  object 
 11  daily_temp_Jan      16760 non-null  float64
 12  daily_temp_Feb      16760 non-null  float64
 13  daily_temp_Mar      16760 non-null  float64
 14  daily_temp_Apr      16760 non-null  float64
 15  daily_temp_May      16760 non-null  float64
 16  dail

In [19]:
# Remove Duplicates if any
merged_df.drop_duplicates(subset='Wine Name', keep='first', inplace=True)

# Drop rows with null values in any of the precipitation columns
precipitation_cols = [col for col in merged_df.columns if 'precipitation' in col]
merged_df.dropna(subset=precipitation_cols, inplace=True)

# Drop rows with null values in any of the temp_max columns
temp_max_cols = [col for col in merged_df.columns if 'MAX' in col]
merged_df.dropna(subset=temp_max_cols, inplace=True)

# Drop rows with null values in any of the temp_max columns
temp_min_cols = [col for col in merged_df.columns if 'MIN' in col]
merged_df.dropna(subset=temp_min_cols, inplace=True)

# Reset the index
merged_df.reset_index(drop=True, inplace=True)

# Save the cleaned dataframe
merged_df.to_csv('data\intermediate\cleaned_merged_data.csv', index=False)

# Check the cleaned dataframe
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15247 entries, 0 to 15246
Data columns (total 59 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Wine Name           15247 non-null  object 
 1   Region 1            15247 non-null  object 
 2   Region 2            15247 non-null  object 
 3   Region 3            15247 non-null  object 
 4   Country             15247 non-null  object 
 5   Score               15247 non-null  int64  
 6   Price               13970 non-null  float64
 7   Winery              15247 non-null  object 
 8   Variety             15196 non-null  object 
 9   Vintage             15247 non-null  int64  
 10  City                15247 non-null  object 
 11  daily_temp_Jan      15247 non-null  float64
 12  daily_temp_Feb      15247 non-null  float64
 13  daily_temp_Mar      15247 non-null  float64
 14  daily_temp_Apr      15247 non-null  float64
 15  daily_temp_May      15247 non-null  float64
 16  dail

Now we will combine the downloaded data with the API fetched data. API fetched data and the downloaded data will need to be standardized to combine them. Also duplicates would need to be removed.

In [24]:
import pandas as pd

# Load the data
cleaned_merged_data = pd.read_csv('data/intermediate/cleaned_merged_data.csv')
weather_enhanced_wine_data = pd.read_csv('data/intermediate/weather_enhanced_wine_data.csv')
cleaned_combined_wine_data = pd.read_csv('data/clean/cleaned_combined_wine_data.csv')

# Standardize column names in weather_enhanced_wine_data
column_name_mapping = {
    'TMAX_': 'daily_temp_MAX_',
    'TMIN_': 'daily_temp_MIN_',
    'PRCP_': 'precipitation_',
    'TAVG_': 'daily_temp_'
}

for original, new in column_name_mapping.items():
    weather_enhanced_wine_data.columns = [
        col.replace(original, new) if original in col else col
        for col in weather_enhanced_wine_data.columns
    ]

# Merging cleaned_merged_data with weather_enhanced_wine_data
merged_data = pd.merge(cleaned_merged_data, weather_enhanced_wine_data, 
                       on=['Wine Name', 'Winery', 'Vintage'], 
                       how='left')

# Fill missing data using cleaned_combined_wine_data
columns_to_fill = ['Region 1', 'Region 2', 'Region 3', 'Score', 'Price', 'Variety']
for col in columns_to_fill:
    if col in cleaned_combined_wine_data:
        fill_values = cleaned_combined_wine_data.set_index(['Wine Name', 'Winery', 'Vintage'])[col]
        merged_data.set_index(['Wine Name', 'Winery', 'Vintage'], inplace=True)
        merged_data[col].fillna(fill_values, inplace=True)
        merged_data.reset_index(inplace=True)

# Standardize weather data column names and reorder them
month_names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
weather_columns = []

for month in month_names:
    weather_columns.extend([
        f'TAVG_{month}', f'TMAX_{month}', f'TMIN_{month}', f'PRCP_{month}'
    ])

for i, month in enumerate(month_names, start=1):
    merged_data.rename(columns={
        f'daily_temp_{month}': f'TAVG_{month}',
        f'daily_temp_MAX_{month}': f'TMAX_{month}',
        f'daily_temp_MIN_{month}': f'TMIN_{month}',
        f'precipitation_{month}': f'PRCP_{month}',
        f'daily_temp_MAX_{i}': f'TMAX_{month}',
        f'daily_temp_MIN_{i}': f'TMIN_{month}',
        f'precipitation_{i}': f'PRCP_{month}',
        f'daily_temp_{i}': f'TAVG_{month}'
    }, inplace=True)

# Remove unwanted columns and duplicates
columns_to_drop = ['City', 'Location Name', 'Address', 'Latitude', 'Longitude']
merged_data.drop(columns=columns_to_drop, errors='ignore', inplace=True)
merged_data.drop_duplicates(subset=['Wine Name', 'Winery', 'Vintage'], inplace=True)
merged_data = merged_data.loc[:,~merged_data.columns.duplicated()]

# Reorder columns to have weather data in the specified order
non_weather_columns = [col for col in merged_data.columns if col not in weather_columns]
final_columns = non_weather_columns + weather_columns
final_data = merged_data[final_columns]

# Save the final DataFrame to a new CSV file
final_data.to_csv('data/intermediate/combined_weather_enhanced_wine_data.csv', index=False)

# Load and inspect the final DataFrame
combined_weather_enhanced_wine_data_df = pd.read_csv('data/intermediate/combined_weather_enhanced_wine_data.csv')
combined_weather_enhanced_wine_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15247 entries, 0 to 15246
Data columns (total 58 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Wine Name  15247 non-null  object 
 1   Winery     15247 non-null  object 
 2   Vintage    15247 non-null  int64  
 3   Region 1   14314 non-null  object 
 4   Region 2   11644 non-null  object 
 5   Region 3   3578 non-null   object 
 6   Country    15247 non-null  object 
 7   Score      15247 non-null  int64  
 8   Price      13970 non-null  float64
 9   Variety    15196 non-null  object 
 10  TAVG_Jan   15247 non-null  float64
 11  TMAX_Jan   15247 non-null  float64
 12  TMIN_Jan   15247 non-null  float64
 13  PRCP_Jan   15247 non-null  float64
 14  TAVG_Feb   15247 non-null  float64
 15  TMAX_Feb   15247 non-null  float64
 16  TMIN_Feb   15247 non-null  float64
 17  PRCP_Feb   15247 non-null  float64
 18  TAVG_Mar   15247 non-null  float64
 19  TMAX_Mar   15247 non-null  float64
 20  TMIN_M

In [15]:
combined_weather_enhanced_wine_data_df.head()

Wine Name                  Winery  \
0  Bodegas Dios Baco S.L. NV 1970 Oxford Pedro Xi...  Bodegas Dios Baco S.L.   
1          Cuva Vella 1980 Vintage Muscat (Valencia)              Cuva Vella   
2  Moulin Touchais 1982 Chenin Blanc (Coteaux du ...         Moulin Touchais   
3  Moulin Touchais 1985 Chenin Blanc (Coteaux du ...         Moulin Touchais   
4  Bodegas Hidalgo 1986 Oloroso Single Vintage Si...         Bodegas Hidalgo   

   Vintage      Region 1   Region 2          Region 3 Country  Score  Price  \
0     1970     Andalucia        NaN             Jerez   SPAIN     85   40.0   
1     1980       Levante        NaN          Valencia   SPAIN     90   65.0   
2     1982  Loire Valley        NaN  Coteaux du Layon  FRANCE     95   64.0   
3     1985  Loire Valley        NaN  Coteaux du Layon  FRANCE     94   72.0   
4     1986         Jerez  Andalucia               NaN   SPAIN     92  155.0   

        Variety  ...  TMIN_Oct  PRCP_Oct  TAVG_Nov  TMAX_Nov  TMIN_Nov  \
0        Sherry  ...      14.3      11.3      17.4      24.3      10.4   
1        Muscat  ...      11.6      94.6      13.5      18.9       8.0   
2  Chenin Blanc  ...      14.0     115.0      12.1      14.1      10.2   
3  Chenin Blanc  ...      14.0     115.0      12.1      14.1      10.2   
4        Sherry  ...      14.3      11.3      17.4      24.3      10.4   

   PRCP_Nov  TAVG_Dec  TMAX_Dec  TMIN_Dec  PRCP_Dec  
0       0.0      13.3      17.5       9.0     163.8  
1      31.4      10.7      14.8       6.6     157.8  
2     106.4       9.8      11.4       8.0     102.8  
3     106.4       9.8      11.4       8.0     102.8  
4       0.0      13.3      17.5       9.0     163.8  

[5 rows x 58 columns]

Since weather_enhanced_wine_data.csv will get continuously updated as I run the script more and more. I need to have an updated script that will combine the updated weather_enhanced_wine_data.csv to combined_weather_enhanced_wine_data.csv.

In [42]:
import pandas as pd
import numpy as np

# Load the data
combined_weather_enhanced_wine_data = pd.read_csv('data/intermediate/combined_weather_enhanced_wine_data.csv')
weather_enhanced_wine_data = pd.read_csv('data/intermediate/weather_enhanced_wine_data.csv')
cleaned_merged_data = pd.read_csv('data/clean/cleaned_combined_wine_data.csv')

# Standardize column names in weather_enhanced_wine_data
month_names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
for i, month in enumerate(month_names, start=1):
    weather_enhanced_wine_data.rename(columns={
        f'TMAX_{i}': f'TMAX_{month}',
        f'TMIN_{i}': f'TMIN_{month}',
        f'PRCP_{i}': f'PRCP_{month}',
        f'TAVG_{i}': f'TAVG_{month}'
    }, inplace=True)

# Convert all weather data columns to float64, converting non-convertible strings to NaN
weather_columns = [f'{prefix}_{month}' for prefix in ['TAVG', 'TMAX', 'TMIN', 'PRCP'] for month in month_names]
for col in weather_columns:
    weather_enhanced_wine_data[col] = pd.to_numeric(weather_enhanced_wine_data[col], errors='coerce')

# Fetch additional data for weather_enhanced_wine_data from cleaned_merged_data
additional_columns = ['Region 1', 'Region 2', 'Region 3', 'Country', 'Score', 'Price', 'Variety']
cleaned_merged_data_subset = cleaned_merged_data[['Wine Name'] + additional_columns]

weather_enhanced_wine_data = pd.merge(weather_enhanced_wine_data, cleaned_merged_data_subset, 
                                      on='Wine Name', how='left')

# Append updated weather_enhanced_wine_data to combined_weather_enhanced_wine_data
updated_combined_data = pd.concat([combined_weather_enhanced_wine_data, weather_enhanced_wine_data])

# Drop duplicates based on Wine Name
updated_combined_data.drop_duplicates(subset='Wine Name', inplace=True)

# Drop rows where any weather data column is null
updated_combined_data.dropna(subset=weather_columns, inplace=True)

# Drop unnecessary columns
columns_to_drop = ['Location Name', 'Address', 'Latitude', 'Longitude']
updated_combined_data.drop(columns=columns_to_drop, inplace=True, errors='ignore')

# Reorder weather columns
tavg_columns = [f'TAVG_{month}' for month in month_names]
tmax_columns = [f'TMAX_{month}' for month in month_names]
tmin_columns = [f'TMIN_{month}' for month in month_names]
prcp_columns = [f'PRCP_{month}' for month in month_names]

weather_columns = tavg_columns + tmax_columns + tmin_columns + prcp_columns
non_weather_columns = [col for col in updated_combined_data.columns if col not in weather_columns]
final_columns = non_weather_columns + weather_columns

updated_combined_data = updated_combined_data[final_columns]

# Sort by increasing vintage and reset index
updated_combined_data.sort_values(by='Vintage', inplace=True)
updated_combined_data.reset_index(drop=True, inplace=True)

# Save the updated DataFrame
updated_combined_data.to_csv('data/intermediate/combined_weather_enhanced_wine_data.csv', index=False)

# Load and inspect the updated DataFrame
updated_combined_weather_enhanced_wine_data_df = pd.read_csv('data/intermediate/combined_weather_enhanced_wine_data.csv')
updated_combined_weather_enhanced_wine_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23671 entries, 0 to 23670
Data columns (total 58 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Wine Name  23671 non-null  object 
 1   Winery     23671 non-null  object 
 2   Vintage    23671 non-null  int64  
 3   Region 1   21028 non-null  object 
 4   Region 2   18661 non-null  object 
 5   Region 3   6054 non-null   object 
 6   Country    23671 non-null  object 
 7   Score      23671 non-null  int64  
 8   Price      21935 non-null  float64
 9   Variety    23308 non-null  object 
 10  TAVG_Jan   23671 non-null  float64
 11  TAVG_Feb   23671 non-null  float64
 12  TAVG_Mar   23671 non-null  float64
 13  TAVG_Apr   23671 non-null  float64
 14  TAVG_May   23671 non-null  float64
 15  TAVG_Jun   23671 non-null  float64
 16  TAVG_Jul   23671 non-null  float64
 17  TAVG_Aug   23671 non-null  float64
 18  TAVG_Sep   23671 non-null  float64
 19  TAVG_Oct   23671 non-null  float64
 20  TAVG_N

In [43]:
updated_combined_weather_enhanced_wine_data_df.head(20)

Wine Name             Winery  \
0                   Calem 1961 Colheita Tawny  (Port)              Calem   
1              Warre's 1961 Reserve Tawny Port (Port)            Warre's   
2               Calem 1961 Colheita Tawny Port (Port)              Calem   
3             Wiese & Krohn 1961 Colheita Port (Port)      Wiese & Krohn   
4                  Cossart Gordon 1962 Bual (Madeira)     Cossart Gordon   
5   Van Zellers 1962 Palmer Colheita White Port (P...        Van Zellers   
6   Quinta da Pacheca 1962 Pacheca Colheita Old Ta...  Quinta da Pacheca   
7                      Dow's 1963 Vintage Port (Port)              Dow's   
8                    Barros 1963 Colheita Port (Port)             Barros   
9                     Burmester 1963 Colheita  (Port)          Burmester   
10                         Dow's 1963 Vintage  (Port)              Dow's   
11                Messias 1963 Colheita Tawny  (Port)            Messias   
12           Taylor Fladgate 1963 Vintage Port (Port)    Taylor Fladgate   
13  C. da Silva 1963 Golden White Colheita Port (P...        C. da Silva   
14                Burmester 1963 Colheita Port (Port)          Burmester   
15            Messias 1963 Colheita Tawny Port (Port)            Messias   
16  W. & J. Graham's 1963 Single Harvest Tawny Por...   W. & J. Graham's   
17                Cockburn's 1963 Vintage Port (Port)         Cockburn's   
18  Taylor Fladgate 1964 Very Old Single Harvest  ...    Taylor Fladgate   
19  Taylor Fladgate 1964 Very Old Single Harvest P...    Taylor Fladgate   

    Vintage Region 1 Region 2 Region 3   Country  Score  Price     Variety  \
0      1961      NaN     Port      NaN  Portugal     95  320.0        Port   
1      1961      NaN     Port      NaN  Portugal     89  111.0  Port Blend   
2      1961      NaN     Port      NaN  Portugal     95  320.0  Port Blend   
3      1961      NaN     Port      NaN  Portugal     92  200.0  Port Blend   
4      1962      NaN  Madeira      NaN  Portugal     96  355.0     Madeira   
5      1962      NaN     Port      NaN  Portugal     90  300.0  Port Blend   
6      1962      NaN     Port      NaN  Portugal     95  500.0  Port Blend   
7      1963      NaN     Port      NaN  Portugal     95  467.0  Port Blend   
8      1963      NaN     Port      NaN  Portugal     91  215.0  Port Blend   
9      1963      NaN     Port      NaN  Portugal     87  790.0        Port   
10     1963      NaN     Port      NaN  Portugal     95  467.0        Port   
11     1963      NaN     Port      NaN  Portugal     96  400.0        Port   
12     1963      NaN     Port      NaN  Portugal     92  430.0  Port Blend   
13     1963      NaN     Port      NaN  Portugal     91  220.0  Port Blend   
14     1963      NaN     Port      NaN  Portugal     87  790.0  Port Blend   
15     1963      NaN     Port      NaN  Portugal     96  400.0  Port Blend   
16     1963      NaN     Port      NaN  Portugal     98  500.0  Port Blend   
17     1963      NaN     Port      NaN  Portugal     90    NaN  Port Blend   
18     1964      NaN     Port      NaN  Portugal     95  588.0        Port   
19     1964      NaN     Port      NaN  Portugal     95  588.0  Port Blend   

    ...  PRCP_Mar  PRCP_Apr   PRCP_May   PRCP_Jun   PRCP_Jul   PRCP_Aug  \
0   ...    3.3580    2.8960   4.378000   4.642000   3.616000   2.724000   
1   ...    3.3580    2.8960   4.378000   4.642000   3.616000   2.724000   
2   ...    3.1050    3.0625   4.737500   4.790000   3.742500   1.772500   
3   ...   56.4000   60.5000  70.966667  83.033333  87.266667  87.833333   
4   ...    2.6140    1.4540   4.568000   4.614000   4.512000   2.496000   
5   ...    2.6140    1.4540   4.568000   4.614000   4.512000   2.496000   
6   ...    2.6140    1.4540   4.568000   4.614000   4.512000   2.496000   
7   ...    3.7460    2.1575   3.738000   2.596000   4.586000   2.268000   
8   ...    3.7460    2.1575   3.738000   2.596000   4.586000   2.268000   
9   ...    3.7460    2.1575   3.738000   2.596000   4.5860

### Simplification of Working Dataframe
Now that we have a workable dataframe, we want to reduce the amount of columns we have by aggregating the monthly weather data to grape growing phases. To do so we also need the dataframe to have ability to identify Northern and Southern hemisphere since the seasons are flipped based on hemisphere. 

In [44]:
# Define a function to determine the hemisphere based on the country
def determine_hemisphere(country):
    """
    Determine the hemisphere of a given country.
    The function checks if the country is in the predefined list of Southern Hemisphere countries.
    If it is, returns 'S'. Otherwise, returns 'N'.
    """
    # List of countries in the Southern Hemisphere
    southern_hemisphere_countries = [
        "Angola", "Argentina", "Australia", "Bolivia", "Botswana", "Brazil",
        "Burundi", "Chile", "Comoros", "DR Congo", "East Timor", "Ecuador",
        "Equatorial Guinea", "Eswatini", "Fiji", "Gabon", "Indonesia", "Kenya",
        "Kiribati", "Lesotho", "Madagascar", "Malawi", "Mauritius", "Mozambique",
        "Namibia", "Nauru", "New Zealand", "Papua New Guinea", "Paraguay", "Peru",
        "Republic of the Congo", "Rwanda", "Samoa", "Sao Tome and Principe",
        "Seychelles", "Solomon Islands", "Somalia", "South Africa", "Tanzania",
        "Tonga", "Tuvalu", "Uganda", "Uruguay", "Vanuatu", "Zambia", "Zimbabwe"
    ]

    # Return 'S' if the country is in the Southern Hemisphere, else 'N'
    return "S" if country in southern_hemisphere_countries else "N"

In [45]:
# Add a new column 'Hemisphere' to the DataFrame
# This is done by applying the 'determine_hemisphere' function to each row in the 'Country' column
updated_combined_weather_enhanced_wine_data_df['Hemisphere'] = updated_combined_weather_enhanced_wine_data_df['Country'].apply(determine_hemisphere)

# Save the modified DataFrame to a new CSV file
updated_combined_weather_enhanced_wine_data_df.to_csv('data/intermediate/combined_weather_enhanced_wine_data_with_Hemisphere.csv', index=False)

# Display the first few rows of the DataFrame to verify the changes
updated_combined_weather_enhanced_wine_data_df.head()

Wine Name          Winery  Vintage Region 1  \
0        Calem 1961 Colheita Tawny  (Port)           Calem     1961      NaN   
1   Warre's 1961 Reserve Tawny Port (Port)         Warre's     1961      NaN   
2    Calem 1961 Colheita Tawny Port (Port)           Calem     1961      NaN   
3  Wiese & Krohn 1961 Colheita Port (Port)   Wiese & Krohn     1961      NaN   
4       Cossart Gordon 1962 Bual (Madeira)  Cossart Gordon     1962      NaN   

  Region 2 Region 3   Country  Score  Price     Variety  ...  PRCP_Apr  \
0     Port      NaN  Portugal     95  320.0        Port  ...    2.8960   
1     Port      NaN  Portugal     89  111.0  Port Blend  ...    2.8960   
2     Port      NaN  Portugal     95  320.0  Port Blend  ...    3.0625   
3     Port      NaN  Portugal     92  200.0  Port Blend  ...   60.5000   
4  Madeira      NaN  Portugal     96  355.0     Madeira  ...    1.4540   

    PRCP_May   PRCP_Jun   PRCP_Jul   PRCP_Aug   PRCP_Sep   PRCP_Oct  PRCP_Nov  \
0   4.378000   4.642000   3.616000   2.724000   2.782000   2.020000     1.884   
1   4.378000   4.642000   3.616000   2.724000   2.782000   2.020000     1.884   
2   4.737500   4.790000   3.742500   1.772500   3.167500   2.235000     1.830   
3  70.966667  83.033333  87.266667  87.833333  79.266667  69.266667    54.500   
4   4.568000   4.614000   4.512000   2.496000   2.704000   1.990000     2.186   

   PRCP_Dec  Hemisphere  
0    2.6980           N  
1    2.6980           N  
2    2.1825           N  
3   41.5000           N  
4    1.0060           N  

[5 rows x 59 columns]

In [46]:
updated_combined_weather_enhanced_wine_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23671 entries, 0 to 23670
Data columns (total 59 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Wine Name   23671 non-null  object 
 1   Winery      23671 non-null  object 
 2   Vintage     23671 non-null  int64  
 3   Region 1    21028 non-null  object 
 4   Region 2    18661 non-null  object 
 5   Region 3    6054 non-null   object 
 6   Country     23671 non-null  object 
 7   Score       23671 non-null  int64  
 8   Price       21935 non-null  float64
 9   Variety     23308 non-null  object 
 10  TAVG_Jan    23671 non-null  float64
 11  TAVG_Feb    23671 non-null  float64
 12  TAVG_Mar    23671 non-null  float64
 13  TAVG_Apr    23671 non-null  float64
 14  TAVG_May    23671 non-null  float64
 15  TAVG_Jun    23671 non-null  float64
 16  TAVG_Jul    23671 non-null  float64
 17  TAVG_Aug    23671 non-null  float64
 18  TAVG_Sep    23671 non-null  float64
 19  TAVG_Oct    23671 non-nul

Now we have the North and Southern Hemisphere distinguished, we would need to average the Weather data based on a Wine Grape's growing cycle, which is as follows:
1. **Budburst and Early Growth (BEG)**
   - Northern Hemisphere: March to May
   - Southern Hemisphere: September to November

2. **Flowering, Fruit Set, and Veraison (FFV)**
   - Northern Hemisphere: May to September
   - Southern Hemisphere: November to March

3. **Harvest and Early Dormancy (HED)**
   - Northern Hemisphere: September to December
   - Southern Hemisphere: March to July

4. **Late Dormancy (LD)**
   - Northern Hemisphere: January to February
   - Southern Hemisphere: August to September

In [ ]:
# Define the growth cycle months for each hemisphere
cycles = {
    'BEG': {'N': ['Mar', 'Apr', 'May'], 'S': ['Sep', 'Oct', 'Nov']},
    'FFV': {'N': ['May', 'Jun', 'Jul', 'Aug', 'Sep'], 'S': ['Nov', 'Dec', 'Jan', 'Feb', 'Mar']},
    'HED': {'N': ['Sep', 'Oct', 'Nov', 'Dec'], 'S': ['Mar', 'Apr', 'May', 'Jun']},
    'LD': {'N': ['Jan', 'Feb'], 'S': ['Jul', 'Aug']}
}

# Weather data types
weather_data_types = ['TAVG', 'TMAX', 'TMIN', 'PRCP']

# Function to calculate the average for a given cycle, hemisphere, and weather data type
def calculate_cycle_average(row, cycle, hemisphere, weather_type):
    months = cycles[cycle][hemisphere]
    return row[[f'{weather_type}_{month}' for month in months]].mean()

# Create new columns and calculate their values
for cycle in cycles:
    for weather_type in weather_data_types:
        column_name = f'{weather_type}_{cycle}'
        updated_combined_weather_enhanced_wine_data_df[column_name] = updated_combined_weather_enhanced_wine_data_df.apply(lambda row: calculate_cycle_average(row, cycle, row['Hemisphere'], weather_type), axis=1)

# Drop the monthly weather data columns
monthly_columns = [f'{weather_type}_{month}' for weather_type in weather_data_types for month in ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']]
updated_combined_weather_enhanced_wine_data_df.drop(monthly_columns, axis=1, inplace=True)

# Save the updated DataFrame (optional)
updated_combined_weather_enhanced_wine_data_df.to_csv('data/clean/updated_wine_data_with_cycle_weather.csv', index=False)

# Display the first few rows to verify
updated_combined_weather_enhanced_wine_data_df.head()

In [41]:
updated_combined_weather_enhanced_wine_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23411 entries, 0 to 23410
Data columns (total 27 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Wine Name   23411 non-null  object 
 1   Winery      23411 non-null  object 
 2   Vintage     23411 non-null  int64  
 3   Region 1    20801 non-null  object 
 4   Region 2    18426 non-null  object 
 5   Region 3    5975 non-null   object 
 6   Country     23411 non-null  object 
 7   Score       23411 non-null  int64  
 8   Price       21700 non-null  float64
 9   Variety     23056 non-null  object 
 10  Hemisphere  23411 non-null  object 
 11  TAVG_BEG    23411 non-null  float64
 12  TMAX_BEG    23411 non-null  float64
 13  TMIN_BEG    23411 non-null  float64
 14  PRCP_BEG    23411 non-null  float64
 15  TAVG_FFV    23411 non-null  float64
 16  TMAX_FFV    23411 non-null  float64
 17  TMIN_FFV    23411 non-null  float64
 18  PRCP_FFV    23411 non-null  float64
 19  TAVG_HED    23411 non-nul